### ISSUE TITLE
Question about chord annotation

### ISSUE THREAD

**Issue by zaocan666** [music-x-lab/POP909-Dataset#4]
Hi~
Great datasets!
I have some doubts about midi chord annotation.
There are chords like C#:maj/3 and Bb:min/b3. I assume "/3" and "/b3" part indicates that the bass note is the third note of the chord.  However, I don't understand the difference between "/3" and "/b3" 
I would really appreciate it if you could explain.

**Comment by RetroCirce** [comment]
Hi~
You can refer to https://www.music-ir.org/mirex/wiki/2020:Audio_Chord_Estimation to find the explanation of chord formats
As for your question:
1.maj/3 means the third note (the middle note) is the bass note as inversion major chord, because a major chord contains 1-3-5.
2. min/b3 means the third note (the middle note) is the bass note, because a minor chord contains 1-b3-5.
Therefore, they are the same. You can find more details in the above website.

**Comment by zaocan666** [comment]
> Hi~
> You can refer to https://www.music-ir.org/mirex/wiki/2020:Audio_Chord_Estimation to find the explanation of chord formats
> As for your question:
> 1.maj/3 means the third note (the middle note) is the bass note as inversion major chord, because a major chord contains 1-3-5.
> 2. min/b3 means the third note (the middle note) is the bass note, because a minor chord contains 1-b3-5.
> Therefore, they are the same. You can find more details in the above website.

thank you very much for answering
