### ISSUE TITLE
Is POP909 available in mxl format?

### ISSUE THREAD

**Issue by sander-wood** [music-x-lab/POP909-Dataset#8]
Hi, is POP909 available in mxl format? I found that some notes in midi are quantized in very strange durations. An example is shown below.

![屏幕截图 2022-09-10 133859](https://user-images.githubusercontent.com/88025106/189470796-cfbe14bb-2bbf-434a-bec4-c1ad2d6649bb.png)

**Comment by RetroCirce** [comment]
Hi, sorry for the late reply,

actually we don't have the mxl format of POP909, but we have a quantized version, you can find it here: https://drive.google.com/file/d/1jKTNI6G7JbTQ6ULluv1JuD5M7JKeW8sX/view?usp=share_link

The time signature is not always correct since we don't label the time signature in the metadata, but they are matching in a fixed tempo.
